services:
  db:
    build:
      context: ./db
    container_name: database-mongo
    ports:
      - "27017:27017"
      
  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8000:80"
    networks:
      - app-node-net
    depends_on:
      - backend

networks:
  app-node-net:
    driver: bridge
      



