services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

volumes:
  wordpress_data:
  db_data:

networks:
  default:
    driver: bridge